source 'https://rubygems.org'

gem 'rails', '3.2.14'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem "mocha", :require => false
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

gem 'devise'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'nokogiri'
gem 'will_paginate', '~> 3.0'
# inline css for emails
gem 'premailer-rails'
# Deploy with Capistrano
gem 'capistrano', '~> 3.0.0'
gem 'capistrano-bundler'
gem 'capistrano-rails'
gem 'capistrano-rvm', '~> 0.0.3'
gem 'delayed_job_active_record'
gem 'daemons'